version: '3'

volumes: 
    web:
    storage:

services:
    web:
        restart: always
        build: ./web
        ports: 
            - "8000:8000"
        depends_on:
            - postgres
            - redis
        env_file: env
        volumes: 
            - web:/data
            - ./web:/data/web
        # command: gunicorn ./gisdrf/gisdrf.wsgi
        command: bash -c "python3 ./gisdrf/manage.py collectstatic --no-input && python3 ./gisdrf/manage.py makemigrations && python3 ./gisdrf/manage.py migrate && python3 ./gisdrf/manage.py runserver 0.0.0.0:8000"


    nginx:
        restart: always
        build: ./nginx/
        depends_on: 
            - web
        ports:
            - "80:80"
        volumes:
            - web:/data
            - ./web/gisdrf/static:/static
        
        
    postgres:
        restart: always
        build: ./postgres
        volumes:
            - storage:/storage
            - ./backups/postgresql:/storage/db/backup
            - ./postgres:/storage/db/
        env_file:
            - env
        expose: 
            - "5432"


    redis:
        restart: always
        image: redis:latest
        expose: 
            - "6379"


    data:
        restart: always
        image: alpine
        volumes:
            - storage:/storage
            - /var/lib/postgresql


    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - env
        ports:
            - "90:80"
        command: "true"